# Generated by Django 2.1 on 2018-08-28 13:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(db_index=True, max_length=32, unique=True)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='statistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.User'),
        ),
    ]
