# Generated by Django 2.1 on 2018-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='data',
        ),
        migrations.AddField(
            model_name='statistics',
            name='action',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_exec_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='fee',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='mid_market_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='pair',
            field=models.CharField(default='BTC_USDT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
